# Generated by Django 3.1 on 2020-08-31 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='portada',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
