# Generated by Django 3.1 on 2020-09-03 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_auto_20200831_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartado',
            name='orden',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apartado',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartados', to='cursos.curso'),
        ),
    ]
