# Generated by Django 3.1 on 2020-09-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_auto_20200903_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartado',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
